FROM mysql:latest

# Establece las variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=Steeven13
ENV MYSQL_DATABASE=myapp
ENV MYSQL_DATABASE=auth
ENV MYSQL_DATABASE=log



# Expon el puerto 3306
EXPOSE 3306